const BlogActionTypes = {
  SET_LOADING: 'SET_LOADING',
  SET_LOGO: 'SET_LOGO',
  GET_POSTS: 'GET_POSTS',
  POSTS_ERROR: 'POSTS_ERROR',
  FILTER_POSTS: 'FILTER_POSTS',
  REG_FALSE: 'REG_FALSE',
  REG_TRUE: 'REG_TRUE',
  CLOSE: 'CLOSE'
};

export default BlogActionTypes;
